---
name: CI

on:
  pull_request:
  push:
  workflow_dispatch:
    inputs:
      debug:
        type: choice
        description: Debug mode
        required: false
        options:
          - "true"
          - "false"

# Allow one concurrent
concurrency:
  group: ${{ format('{0}-{1}', github.event_name, github.ref) }}
  cancel-in-progress: true

env:
  DEBUG: ${{ inputs.debug || secrets.ACTIONS_RUNNER_DEBUG || vars.ACTIONS_RUNNER_DEBUG || secrets.ACTIONS_STEP_DEBUG || vars.ACTIONS_STEP_DEBUG || false }}

jobs:
  lint:
    name: Lint
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Run pre-commit
        run: |
          pip install pre-commit
          pre-commit run --all-files --verbose

  dog-food-matrix:
    name: Dog food (test runners)
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: actionlint Action
        id: actionlint
        uses: ./
        with:
          flags: "-ignore SC2086"
          fail-on-error: false

      - name: actionlint Summary
        if: ${{ always() }}
        run: |
          echo "Used actionlint version ${{ steps.actionlint.outputs.version-semver }}"
          echo "Used actionlint release ${{ steps.actionlint.outputs.version-tag }}"
          echo "actionlint ended with ${{ steps.actionlint.outputs.exit-code }} exit code"
          echo "actionlint ended because '${{ steps.actionlint.outputs.exit-message }}'"
          echo "actionlint found ${{ steps.actionlint.outputs.total-errors }} errors"
          echo "actionlint checked ${{ steps.actionlint.outputs.total-files }} files"
          echo "actionlint cache used: ${{ steps.actionlint.outputs.cache-hit }}"
          # shellcheck disable=SC2242
          exit ${{ steps.actionlint.outputs.exit-code }}

  dog-food:
    name: Dog food (test inputs)
    needs:
      - dog-food-matrix
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: actionlint Action (old version)
        uses: ./
        with:
          version: "1.6.23"
          shellcheck: false
          pyflakes: false
          files: "tests/*.yml, tests/*.yaml"
          flags: "-ignore SC2086"
          fail-on-error: false

      - name: actionlint Action (test broken)
        id: actionlint
        uses: ./
        with:
          files: "tests/*.yml, tests/*.yaml"
          flags: "-ignore SC2086"
          fail-on-error: false

      - name: actionlint Summary
        if: ${{ steps.actionlint.outputs.exit-code != '0' }}
        run: |
          echo "Used actionlint version ${{ steps.actionlint.outputs.version-semver }}"
          echo "Used actionlint release ${{ steps.actionlint.outputs.version-tag }}"
          echo "actionlint ended with ${{ steps.actionlint.outputs.exit-code }} exit code"
          echo "actionlint ended because '${{ steps.actionlint.outputs.exit-message }}'"
          echo "actionlint found ${{ steps.actionlint.outputs.total-errors }} errors"
          echo "actionlint checked ${{ steps.actionlint.outputs.total-files }} files"
          echo "actionlint cache used: ${{ steps.actionlint.outputs.cache-hit }}"
