---
name: Draft Release

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - main

jobs:
  draft-release:
    name: Draft Release
    uses: raven-actions/.workflows/.github/workflows/__release-draft.yml@main
    secrets: inherit
